# Generated by Django 2.2.7 on 2019-11-28 05:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ordemServico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nrOS', models.CharField(max_length=20, verbose_name='Ordem de Serviço')),
                ('tpPedido', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ordem')),
                ('tpOperacao', models.CharField(max_length=20, null=True, verbose_name='Tipo de Operação')),
                ('dsOS', models.CharField(max_length=200, null=True, verbose_name='Descrição')),
                ('nmCliente', models.CharField(default='deixar nome usuario logado', max_length=30, null=True, verbose_name='Nome do Cliente')),
                ('nmColaborador', models.CharField(default='Nome do colaborador', max_length=30, null=True, verbose_name='Nome do Cliente')),
                ('status', models.CharField(choices=[('em andamento', 'em andamento'), ('pendente', 'pendente'), ('rejeitado', 'rejeitado'), ('finalizado', 'finalizado'), ('transporte', 'transporte'), ('Solicitar retirada', 'Solicitar retirada'), ('Confirmar retirada', 'Confirmar retirada')], default='Solicitar retirada', max_length=18, null=True, verbose_name='Status')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Valor Total')),
                ('dtSaida', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Saída')),
                ('dtEntrada', models.DateField(blank=True, null=True, verbose_name='Entrada')),
                ('peso1', models.IntegerField(blank=True, null=True, verbose_name='Peso aproximado em KGs')),
                ('peso2', models.IntegerField(blank=True, null=True, verbose_name='Peso real')),
                ('qteTotal', models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantidade Total')),
                ('finalizado', models.BooleanField(blank=True, null=True)),
                ('faturado', models.BooleanField(default=False)),
                ('dt_fat', models.DateField(blank=True, null=True, verbose_name='Data de Faturado')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de serviço',
            },
        ),
        migrations.CreateModel(
            name='ordemServicoItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nrItem', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nr Controle Pedido')),
                ('qte', models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantidade')),
                ('dt_entrada', models.DateField(blank=True, null=True, verbose_name='Entrada')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Valor')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Total')),
                ('peso1', models.IntegerField(blank=True, null=True, verbose_name='Peso aproximado em KGs')),
                ('peso2', models.IntegerField(blank=True, null=True, verbose_name='Peso real')),
                ('obs', models.CharField(blank=True, max_length=90, null=True, verbose_name='Observação')),
                ('ordemServico', models.ForeignKey(blank=True, max_length=90, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitacao.ordemServico')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
    ]
