# Generated by Django 2.2.7 on 2019-11-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemservico',
            old_name='dt_fat',
            new_name='dtFat',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='tpPedido',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tpOS',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de Ordem'),
        ),
    ]
