# Generated by Django 2.2.7 on 2019-11-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0002_auto_20191128_0333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemservicoitem',
            old_name='dt_entrada',
            new_name='dtEntrada',
        ),
    ]
