# Generated by Django 2.2.7 on 2019-11-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0003_auto_20191128_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='peso1',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='peso2',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='pesoTotal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Peso Total'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='nmColaborador',
            field=models.CharField(max_length=30, null=True, verbose_name='colaborador'),
        ),
    ]
