# Generated by Django 2.2.7 on 2019-12-12 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0005_auto_20191128_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='solicitarRetirada',
            fields=[
            ],
            options={
                'verbose_name': 'Solicitar retirada de material',
                'verbose_name_plural': 'Retirada de Materiais',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('solicitacao.ordemservico',),
        ),
    ]
