# Generated by Django 2.2.7 on 2020-01-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0006_solicitarretirada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('em andamento', 'em andamento'), ('pendente', 'pendente'), ('rejeitado', 'rejeitado'), ('finalizado', 'finalizado'), ('transporte', 'transporte'), ('Solicitar retirada', 'Solicitar retirada'), ('Confirmar retirada', 'Confirmar retirada'), ('Solicitar cacamba', 'Solicitar cacamba')], default='Solicitar retirada', max_length=18, null=True, verbose_name='Status'),
        ),
    ]
