# Generated by Django 2.2.7 on 2019-11-13 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nm_cidade', models.CharField(blank=True, max_length=50, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': '2. Cidade',
            },
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nm_estado', models.CharField(blank=True, max_length=50, verbose_name='Estado')),
            ],
            options={
                'verbose_name': '3. Estado',
            },
        ),
        migrations.CreateModel(
            name='fornecedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nm_fornecedor', models.CharField(max_length=55, verbose_name='Nome do fornecedor')),
                ('cnpj', models.CharField(blank=True, max_length=25, null=True)),
                ('categoria', models.CharField(blank=True, max_length=40, null=True)),
                ('endereco', models.CharField(blank=True, max_length=90, null=True)),
                ('num', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=70, null=True)),
                ('bairro', models.CharField(blank=True, max_length=80, null=True)),
                ('cep', models.CharField(blank=True, max_length=15, null=True)),
                ('ddd1', models.CharField(blank=True, max_length=4, null=True, verbose_name='DDD')),
                ('fone1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Principal')),
                ('ddd2', models.CharField(blank=True, max_length=4, null=True, verbose_name='DDD')),
                ('fone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone de apoio')),
                ('contato', models.CharField(blank=True, max_length=60, null=True)),
                ('comprador', models.CharField(blank=True, max_length=60, null=True, verbose_name='Comprador')),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('nr_banco', models.IntegerField(blank=True, null=True)),
                ('banco', models.CharField(blank=True, max_length=40, null=True)),
                ('tp_conta', models.CharField(blank=True, max_length=20, null=True)),
                ('agencia', models.CharField(blank=True, max_length=15, null=True)),
                ('nr_conta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da conta')),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('obs', models.CharField(blank=True, max_length=90, null=True)),
                ('cidade', models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.cidade')),
                ('estado', models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.estado')),
            ],
            options={
                'verbose_name': '1. Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='cadastro_geral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nm', models.CharField(max_length=55, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=25, null=True)),
                ('categoria', models.CharField(blank=True, max_length=40, null=True)),
                ('endereco', models.CharField(blank=True, max_length=90, null=True)),
                ('num', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=70, null=True)),
                ('bairro', models.CharField(blank=True, max_length=80, null=True)),
                ('cep', models.CharField(blank=True, max_length=15, null=True)),
                ('ddd1', models.CharField(blank=True, max_length=4, null=True, verbose_name='DDD')),
                ('fone1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Principal')),
                ('ddd2', models.CharField(blank=True, max_length=4, null=True, verbose_name='DDD')),
                ('fone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone de apoio')),
                ('contato', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('nr_banco', models.IntegerField(blank=True, null=True)),
                ('banco', models.CharField(blank=True, max_length=40, null=True)),
                ('tp_conta', models.CharField(blank=True, max_length=20, null=True)),
                ('agencia', models.CharField(blank=True, max_length=15, null=True)),
                ('nr_conta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da conta')),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('obs', models.CharField(blank=True, max_length=90, null=True)),
                ('cidade', models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.cidade')),
                ('estado', models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.estado')),
            ],
            options={
                'verbose_name': '1. Cadastro',
            },
        ),
    ]
