# Generated by Django 2.2.7 on 2019-11-16 22:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='historicocacamba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desCacamba', models.CharField(blank=True, max_length=50, verbose_name='Descricao do problema')),
                ('dthistCacamba', models.DateField(default=datetime.datetime(2019, 11, 16, 19, 12, 55, 547211), verbose_name='Data de Registro')),
            ],
        ),
        migrations.CreateModel(
            name='tipocacamba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tpCacamba', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Cacamba')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cadastro_geral',
            options={'verbose_name': '1. Cadastro (Clique aqui para adicionar usando XLS)'},
        ),
        migrations.CreateModel(
            name='cacamba',
            fields=[
                ('nrcacamba', models.AutoField(primary_key=True, serialize=False)),
                ('espCacamba', models.CharField(blank=True, max_length=100, verbose_name='Especificacao')),
                ('capCacamba', models.CharField(blank=True, max_length=10, verbose_name='Capacidade')),
                ('sttCacamba', models.IntegerField(verbose_name='Status')),
                ('tamCacamba', models.IntegerField(verbose_name='Tampa')),
                ('traCacamba', models.IntegerField(verbose_name='Trava')),
                ('funCacamba', models.IntegerField(verbose_name='Fundo')),
                ('argCacamba', models.IntegerField(verbose_name='Argola')),
                ('pinCacamba', models.IntegerField(verbose_name='Pintura')),
                ('tpCacamba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.tipocacamba', verbose_name='Tipo de Cacamba')),
            ],
        ),
    ]
