# Generated by Django 2.2.7 on 2019-11-16 23:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20191116_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cacamba',
            options={'verbose_name': '4. Cacamba'},
        ),
        migrations.AlterField(
            model_name='historicocacamba',
            name='dthistCacamba',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data de Registro'),
        ),
    ]
