# Generated by Django 2.2.7 on 2019-11-16 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20191116_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicocacamba',
            name='dthistCacamba',
        ),
    ]
