# Generated by Django 2.2.7 on 2019-11-16 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_remove_historicocacamba_dthistcacamba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='historicocacamba',
        ),
        migrations.AlterModelOptions(
            name='cadastro_geral',
            options={},
        ),
    ]
