# Generated by Django 2.2.7 on 2019-11-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_auto_20191116_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='historicocacamba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desCacamba', models.CharField(blank=True, max_length=50, verbose_name='Descricao do problema')),
            ],
        ),
    ]
