# Generated by Django 2.2.7 on 2019-11-16 23:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_historicocacamba'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicocacamba',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Registro'),
        ),
    ]
