# Generated by Django 2.2.7 on 2019-11-16 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_historicocacamba_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacamba',
            name='htcacamba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.historicocacamba', verbose_name='Historico da cacamba'),
        ),
    ]
