# Generated by Django 2.2.7 on 2019-11-16 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_cacamba_htcacamba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacamba',
            name='htcacamba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.historicocacamba', verbose_name='Historico da cacamba'),
        ),
    ]
