# Generated by Django 2.2.7 on 2019-11-17 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_auto_20191116_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocacamba',
            options={'verbose_name': 'Tipos de Cacambas'},
        ),
        migrations.AlterField(
            model_name='cacamba',
            name='tpCacamba',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.tipocacamba', verbose_name='Tipo de Cacamba'),
        ),
        migrations.AlterField(
            model_name='historicocacamba',
            name='desCacamba',
            field=models.CharField(blank=True, max_length=300, verbose_name='Descricao do problema'),
        ),
        migrations.AlterField(
            model_name='tipocacamba',
            name='tpCacamba',
            field=models.CharField(blank=True, max_length=30, verbose_name='Tipo de Cacamba'),
        ),
    ]
