# Generated by Django 2.2.7 on 2019-11-17 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_auto_20191116_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='colaborador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nm_colaborador', models.CharField(max_length=55, verbose_name='Nome do fornecedor')),
                ('cnpj', models.CharField(blank=True, max_length=25, null=True)),
                ('funcao', models.CharField(blank=True, max_length=60, null=True)),
                ('endereco', models.CharField(blank=True, max_length=90, null=True)),
                ('num', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=70, null=True)),
                ('bairro', models.CharField(blank=True, max_length=80, null=True)),
                ('cep', models.CharField(blank=True, max_length=15, null=True)),
                ('ddd1', models.CharField(blank=True, max_length=4, null=True, verbose_name='DDD')),
                ('fone1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Principal')),
                ('ddd2', models.CharField(blank=True, max_length=4, null=True, verbose_name='DDD')),
                ('fone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone de apoio')),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('nr_banco', models.IntegerField(blank=True, null=True)),
                ('banco', models.CharField(blank=True, max_length=40, null=True)),
                ('tp_conta', models.CharField(blank=True, max_length=20, null=True)),
                ('agencia', models.CharField(blank=True, max_length=15, null=True)),
                ('nr_conta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da conta')),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('obs', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'verbose_name': '1. Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='identidadejuridica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nm', models.CharField(max_length=55, verbose_name='Razao Social')),
                ('cnpj', models.CharField(blank=True, max_length=25, null=True)),
                ('categoria', models.CharField(blank=True, max_length=40, null=True)),
                ('endereco', models.CharField(blank=True, max_length=90, null=True, verbose_name='Endereco Matriz')),
                ('num', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=70, null=True)),
                ('bairro', models.CharField(blank=True, max_length=80, null=True, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=15, null=True, verbose_name='CEP Matriz')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pais sede')),
                ('ddd1', models.CharField(blank=True, max_length=4, null=True, verbose_name='DDD')),
                ('fone1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Principal')),
                ('ddd2', models.CharField(blank=True, max_length=4, null=True, verbose_name='DDD')),
                ('fone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone de apoio')),
                ('contato', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=60, null=True, verbose_name='E-mail juridico')),
                ('endereco_op', models.CharField(blank=True, max_length=90, null=True, verbose_name='Endereco Operacional')),
                ('complemento_op', models.CharField(blank=True, max_length=70, null=True, verbose_name='Complemento Operacional')),
                ('bairro_op', models.CharField(blank=True, max_length=80, null=True, verbose_name='Bairro Operacional')),
                ('cep_op', models.CharField(blank=True, max_length=15, null=True, verbose_name='CEP Operacional')),
                ('pais_op', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pais Operacional')),
                ('ddd1_op', models.CharField(blank=True, max_length=4, null=True, verbose_name='DDD Operacional')),
                ('fone1_op', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Operacional')),
                ('nr_banco', models.IntegerField(blank=True, null=True, verbose_name='Numero do banco')),
                ('banco', models.CharField(blank=True, max_length=40, null=True, verbose_name='Banco')),
                ('tp_conta', models.CharField(blank=True, max_length=20, null=True, verbose_name='tipo de conta')),
                ('agencia', models.CharField(blank=True, max_length=15, null=True, verbose_name='Agencia')),
                ('nr_conta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da conta')),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='estado',
        ),
        migrations.AlterModelOptions(
            name='cacamba',
            options={'verbose_name': '2. Cacamba'},
        ),
        migrations.AlterModelOptions(
            name='cidade',
            options={'verbose_name': 'Cidade'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado'},
        ),
        migrations.DeleteModel(
            name='cadastro_geral',
        ),
        migrations.DeleteModel(
            name='fornecedor',
        ),
        migrations.AddField(
            model_name='identidadejuridica',
            name='cidade',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.cidade', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='identidadejuridica',
            name='estado',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cidade',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.cidade'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='estado',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.estado'),
        ),
    ]
