# Generated by Django 2.2.7 on 2019-11-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_auto_20191128_0251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'verbose_name': '5. Cidade'},
        ),
        migrations.AlterModelOptions(
            name='colaborador',
            options={'verbose_name': '2. Colaborador', 'verbose_name_plural': '2. Colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': '6. Estado'},
        ),
        migrations.AlterModelOptions(
            name='tipocacamba',
            options={'verbose_name': '4. Tipos de Cacamba'},
        ),
        migrations.AlterField(
            model_name='cacamba',
            name='argCacamba',
            field=models.IntegerField(blank=True, verbose_name='Argola'),
        ),
        migrations.AlterField(
            model_name='cacamba',
            name='funCacamba',
            field=models.IntegerField(blank=True, verbose_name='Fundo'),
        ),
        migrations.AlterField(
            model_name='cacamba',
            name='pinCacamba',
            field=models.IntegerField(blank=True, verbose_name='Pintura'),
        ),
        migrations.AlterField(
            model_name='cacamba',
            name='sttCacamba',
            field=models.IntegerField(blank=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cacamba',
            name='tamCacamba',
            field=models.IntegerField(blank=True, verbose_name='Tampa'),
        ),
        migrations.AlterField(
            model_name='cacamba',
            name='traCacamba',
            field=models.IntegerField(blank=True, verbose_name='Trava'),
        ),
    ]
