# Generated by Django 2.2.7 on 2019-11-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0016_auto_20191128_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacamba',
            name='argCacamba',
            field=models.IntegerField(blank=True,  null=True, verbose_name='Argola'),
        ),
        migrations.AlterField(
            model_name='cacamba',
            name='funCacamba',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fundo'),
        ),
        migrations.AlterField(
            model_name='cacamba',
            name='pinCacamba',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pintura'),
        ),
        migrations.AlterField(
            model_name='cacamba',
            name='tamCacamba',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tampa'),
        ),
        migrations.AlterField(
            model_name='cacamba',
            name='traCacamba',
            field=models.IntegerField(blank=True, null=True, verbose_name='Trava'),
        ),
    ]
