# Generated by Django 2.2.7 on 2019-11-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0016_auto_20191128_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacamba',
            name='sttCacamba',
            field=models.IntegerField(blank=True, default='status', verbose_name='Status'),
            preserve_default=False,
        ),
    ]
