# Generated by Django 2.2.6 on 2019-10-14 21:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedidos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nr_pedido', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nr Controle Pedido')),
                ('tp_pedido', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ordem')),
                ('qte', models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantidade')),
                ('dt_saida', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Saída')),
                ('dt_entrada', models.DateField(blank=True, null=True, verbose_name='Entrada')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Valor')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Total')),
                ('status', models.CharField(choices=[('em andamento', 'em andamento'), ('pendente', 'pendente'), ('rejeitado', 'rejeitado'), ('finalizado', 'finalizado'), ('transporte', 'transporte'), ('Solicitar retirada', 'Solicitar retirada'), ('Confirmar retirada', 'Confirmar retirada')], default='Solicitar retirada', max_length=18, null=True, verbose_name='Status')),
                ('cacamba', models.CharField(choices=[('pole', 'pole'), ('rolon', 'rolon'), ('muk', 'muk')], max_length=6, null=True, verbose_name='Tipos de Cacambas')),
                ('peso1', models.IntegerField(blank=True, null=True, verbose_name='Peso aproximado em KGs')),
                ('peso2', models.IntegerField(blank=True, null=True, verbose_name='Peso real')),
                ('obs', models.CharField(blank=True, max_length=90, null=True, verbose_name='Observação')),
                ('finalizado', models.BooleanField(blank=True, null=True)),
                ('faturado', models.BooleanField(default=False)),
                ('dt_fat', models.DateField(blank=True, null=True, verbose_name='Data de Faturado')),
                ('fornecedor', models.ForeignKey(blank=True, max_length=90, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.cadastro_geral')),
            ],
            options={
                'verbose_name': 'Pedidos - Sudeste',
                'verbose_name_plural': 'Pedidos - Sudeste',
            },
        ),
        migrations.CreateModel(
            name='pedidosFaturamento',
            fields=[
            ],
            options={
                'verbose_name': 'Faturamento de Pedido',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reciclavel.pedidos',),
        ),
        migrations.CreateModel(
            name='pedidosLista',
            fields=[
            ],
            options={
                'verbose_name': 'retirada de material',
                'verbose_name_plural': 'Retirada de Materiais',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reciclavel.pedidos',),
        ),
    ]
